version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_statedu
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || echo 'Superuser yaratilmadi.' &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8580:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - database
      - redis
    restart: always

  database:
    image: postgres:15
    container_name: postgres_statedu
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis_statedu
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker_statedu
    command: celery -A core worker --loglevel=info
    depends_on:
      - web
      - redis
    env_file:
      - .env
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat_statedu
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - web
      - redis
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
