# Generated by Django 5.1.4 on 2025-01-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='statisticssnapshot',
            options={'ordering': ['id']},
        ),
    ]
